[project]
name = "wuji-retargeting"
version = "0.1.0-rc.5"
description = "High-precision hand pose retargeting system for WujiHand"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = [
    "numpy>=1.21.0",
    "nlopt",
    "pin>=3.8.0",
    "pyyaml",
]

[tool.setuptools]
packages = ["wuji_retargeting"]

[tool.setuptools.package-data]
"wuji_retargeting" = [
    "urdf/*.urdf",
    "meshes/**/*.STL",
]
